#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

# Duas tela
#bspc monitor eDP I II III IV 
#bspc monitor HDMI-A-0 V VI VII VIII IX X


bspc config border_width        2
bspc config window_gap          5
bspc config active_border_color "#FFFFFF"
bspc config normal_border_color "#434c5e"


bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Rules
# xprop | grep WM_CLASS

bspc rule -a File-roller state=floating rectangle=800x600+275+100

# bspc rule -a PolyMC state=floating rectangle=800x600+275+100
# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a firefox desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

# Auto Start

setxkbmap br &

# Cursor Fix
#lxappearance &

# Picom
picom &

# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# NotifyD
/usr/lib/xfce4/notifyd/xfce4-notifyd &

# Nitrogen
nitrogen --restore &

# Cursor fix
xsetroot -cursor_name left_ptr

# Polybar
${HOME}/.config/polybar/launch.sh --blocks
